export const APP_CONFIG = {
  name: 'AI Laptop Review',
  version: '2.0.0',
  defaultGeminiModel: 'gemini-3.8-flash',
  maxCompareLaptops: 3,
  jobTimeoutMs: 60000,
  maxExtractionAttempts: 3,
};

export const ERROR_CODES = {
  // Client & Validation
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_YOUTUBE_URL: 'INVALID_YOUTUBE_URL',
  DUPLICATE_VIDEO: 'DUPLICATE_VIDEO',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',

  // Gemini & Ingestion
  GEMINI_NOT_CONFIGURED: 'GEMINI_NOT_CONFIGURED',
  GEMINI_AUTH_FAILED: 'GEMINI_AUTH_FAILED',
  GEMINI_TIMEOUT: 'GEMINI_TIMEOUT',
  GEMINI_RATE_LIMIT: 'GEMINI_RATE_LIMIT',
  GEMINI_EXTRACTION_FAILED: 'GEMINI_EXTRACTION_FAILED',
  GEMINI_SCHEMA_ERROR: 'GEMINI_SCHEMA_ERROR',

  // Database & Persistence
  DATABASE_NOT_CONFIGURED: 'DATABASE_NOT_CONFIGURED',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',

  // Retail Scraper
  RETAIL_FETCH_FAILED: 'RETAIL_FETCH_FAILED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

export const BENCHMARK_CATEGORIES = [
  'cpu',
  'gpu',
  'rendering',
  'ai',
  'storage',
  'system',
  'productivity',
] as const;

export const RESOLUTION_STANDARDS: Record<string, string> = {
  '1080p': '1920x1080',
  '1200p': '1920x1200',
  '1440p': '2560x1440',
  '1600p': '2560x1600',
  '4k': '3840x2160',
};
